version: 2.1

executors:
  mac:
    macos:
      xcode: '13.4.1'

commands:
  restore:
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package-lock.json" }}

jobs:
  install:
    executor: mac
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: node_modules-{{checksum "package-lock.json" }}
          paths:
            - node_modules

  test:
    executor: mac
    steps:
      - restore
      - run:
          name: Test
          command: npm test -- --ci --runInBand
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit
      - store_test_results:
          path: ./reports/junit
      - store_artifacts:
          path: coverage

  e2e:
    executor: mac
    steps:
      - restore
      - run: npm i -g detox-cli expo-cli
      - run: brew tap wix/brew
      - run: brew install applesimutils
      - run: detox clean-framework-cache && detox build-framework-cache
      - run: expo prebuild -p ios
      - run: detox build -c ios
      - run:
          name: E2E
          command: npm run e2e -- -c ios --record-videos all --artifacts-location ./reports/records
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit
      - store_test_results:
          path: ./reports/junit
      - store_artifacts:
          path: ./reports/records

  expo-publish-release-channel:
    executer: mac
    steps:
      - restore
      - run: npx expo-cli publish --non-interactive --max-workers 1 release-channel $(echo $CIRCLE_BRANCH | tr A-Z a-z)

  expo-publish:
    executer: mac
    steps:
      - restore
      - run: npx expo-cli publish --non-interactive --max-workers 1

workflows:
  main:
    jobs:
      - install
      - e2e:
          requires:
            - install
      - publish:
          requires:
            - install
            - e2e
          filters:
            branches:
              only: master
      - publish-release-channel:
          requires:
            - install
            - e2e
          filters:
            branches:
              ignore:
                - master


