version: 2.1

executors:
  mac:
    macos:
      xcode: '13.0.0'

commands:
  restore:
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package-lock.json" }}

jobs:
  install:
    executor: mac
    steps:
      - checkout
      - run: npm ci
      - save_cache:
          key: node_modules-{{checksum "package-lock.json" }}
          paths:
            - node_modules

  test:
    executor: mac
    steps:
      - restore
      - run:
          name: Test
          command: npm test -- --ci --runInBand --reporters=default --reporters=jest-junit --coverage=true
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit
      - store_test_results:
          path: ./reports/junit
      - store_artifacts:
          path: coverage

  e2e:
    executor: mac
    steps:
      - restore
      - run: ./scripts/e2e.sh
      - run:
          name: E2E
          command: npm run e2e -- -c ios
      - store_test_results:
          path: ./reports/junit
      - store_artifacts:
          path: coverage

workflows:
  main:
    jobs:
      - install
      - test:
          requires:
            - install
      - e2e:
          requires:
            - install

